[[edge_functions]]
  path = "/*"
  excludedPath = "/.netlify/*"
  excludedPath = "/manifest.json"
  excludedPath = "/favicon.ico"
  excludedPath = "/logo192.png"
  excludedPath = "/logo512.png"
  excludedPath = "/apple-touch-icon.png"
  function = "auth"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
